---
locale_lang: de_DE.UTF-8
locale_all: de_DE.UTF-8

base_packages:
  - curl
  - nano
  - htop
  - ca-certificates
  - bash-completion

ntp_enabled: true

ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org

# SSH hardening (minimal, homelab-friendly)
ssh_disable_password_auth: true
ssh_permit_root_login: true
ssh_max_auth_tries: 3

# SSH authorized keys (root)
ssh_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL0AEc/tceHaOknKQgHSmWZ+lEk8HSPgSGMoQYHM8D1Z christoph.schwaeppe@gmail.com
"
ssh_authorized_keys_exclusive: true
