all:
  children:
    proxmox_hosts:
      hosts:
        pve-01:
          ansible_host: 192.168.1.26
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3.11

    docker_hosts:
      hosts:
        docker-vm:
          ansible_host: 192.168.1.63
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3

    nginx_hosts:
      hosts:
        nginx-lxc:
          ansible_host: 192.168.1.30
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3

    docker_base:
      hosts:
        docker-base:
          ansible_host: 192.168.1.113
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3

    nginx_base:
      hosts:
        nginx-base:
          ansible_host: 192.168.1.114
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3


    ci_hosts:
      hosts:
        ci-debian12-base:
          ansible_host: 192.168.1.112
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
