---
# --------------------------------------------------
# Base packages (safe defaults)
# --------------------------------------------------
base_packages: []

# --------------------------------------------------
# Locale defaults
# --------------------------------------------------
locale_lang: C.UTF-8
locale_all: C.UTF-8

# --------------------------------------------------
# NTP defaults
# --------------------------------------------------
ntp_enabled: false
ntp_servers: []

# --------------------------------------------------
# qemu-guest-agent defaults
# --------------------------------------------------
enable_qemu_guest_agent: false

# --------------------------------------------------
# SSH hardening defaults
# --------------------------------------------------
ssh_max_auth_tries: 6
ssh_authorized_keys: []
ssh_authorized_keys_exclusive: false
