#SPDX-License-Identifier: MIT-0
---
# --------------------------------------------------
# Docker daemon defaults
# --------------------------------------------------
docker_daemon_config:
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"
  live-restore: true
